title: 'GSoC 2021 Tracker'

header_pages:
  - index.md
  - about.md
  - notes.md
  - report.md
  
style: dark

footer: 'follow me on <a href="https://github.com/VedantParanjape">github</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
